# Generated by Django 3.1 on 2023-07-08 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_category_offer_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offer_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
