# Generated by Django 3.1 on 2023-07-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_referralcoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcoupon',
            name='amount',
        ),
        migrations.AlterField(
            model_name='referralcoupon',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
