# Generated by Django 3.1 on 2023-07-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230712_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralcoupon',
            old_name='generated_by',
            new_name='generated_by_account',
        ),
        migrations.AddField(
            model_name='account',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
