# Generated by Django 3.1 on 2023-07-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20230710_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('shipped', 'shipped'), (' Completed', ' Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
    ]
