# Generated by Django 3.1 on 2023-07-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('shipped', 'shipped'), (' Delivered', ' Delivered'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
    ]
