# Generated by Django 3.1 on 2023-07-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_addaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addaddress',
            old_name='address_line_1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='addaddress',
            old_name='address_line_2',
            new_name='address_line2',
        ),
    ]
