# Generated by Django 3.1 on 2023-07-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20230715_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='refund_status',
            field=models.CharField(choices=[('Requested', 'Return Requested'), ('Initiated', 'Refund Initiated'), ('Refunded', 'Refunded')], default='Requested', max_length=20),
        ),
    ]
